-- Copy and paste this into the SQL Editor in your Supabase Dashboard

-- 1. Create Expenses Table
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  date date,
  business text,
  amount numeric,
  category text,
  notes text,
  month text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Categories Table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Mapping Table
create table if not exists mapping (
  id bigint generated by default as identity primary key,
  business text unique not null,
  category text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable Row Level Security (RLS) - Optional for personal project but recommended
alter table expenses enable row level security;
alter table categories enable row level security;
alter table mapping enable row level security;

-- 5. Create Policies to allow access (Modify if you need specific user auth)
-- For simple service_role access or Anon key access (if you want public read/write for your app)
-- Note: Replace 'anon' with specific roles if needed. 
-- Assuming you use the key from secrets in backend, it might bypass RLS if service_role used, 
-- but 'supabase-py' usually uses Anon key by default unless configured otherwise.

create policy "Enable all access for all users" on expenses for all using (true);
create policy "Enable all access for all users" on categories for all using (true);
create policy "Enable all access for all users" on mapping for all using (true);
